declare enum EffectTypes {
    CHARACTER_MOVED = "CHARACTER_MOVED",
    CHARACTER_ROTATED = "CHARACTER_ROTATED",
    DAMAGE_ON_CHARACTER = "DAMAGE_ON_CHARACTER",
    HEALTH_CHANGE_ON_CHARACTER = "HEALTH_CHANGE_ON_CHARACTER"
}
export default EffectTypes;
